name: Sync Backend

on:
  push:
    branches:
      - fullstack 
  workflow_dispatch: 

jobs:
  push-subtrees:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout fullstack
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.BACKEND_KEY }}

      
      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

     
      - name: Add backend remote
        run: git remote add backend-remote git@github.com:OPSILab/Data-model-mapper-backend.git || echo "Remote already exists"
     
      - name: Push backend subtree
        run: git subtree push --prefix=backend backend-remote main || echo "No changes"
